FROM ruby:3.3.6

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
ENV RAILS_ENV=development

RUN apt-get update -qq && apt-get install -y \
  ca-certificates \
  curl \
  gnupg \
  postgresql-client \
  build-essential \
  libpq-dev \
  nodejs \
  npm \
  git \
  vim

RUN npm install -g yarn

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install

COPY . .